### ISSUE TITLE
Example 대로 실행하였는데 에러가 나네요.

### ISSUE THREAD

**Issue by dkstm95** [lumyjuwon/KoreaNewsCrawler#10]
Your program is still running! Do you want to kill it?

이라고 에러가 뜨네요.

ReadME의 Example 그대로 실행해보았는데 무엇이 잘못되었을까요?

**Comment by dkstm95** [comment]
set_category를 "정치" 하나만 줘도 에러가 나네요.

**Comment by dkstm95** [comment]
Your program is still running! Do you want to kill it? 라고 똑같은 에러가 뜹니다.

**Comment by lumyjuwon** [comment]
사용하고 계신 파이썬 버전 및 OS 알려주시고, KoreaNewsCrawler 라이브러리 버전도 확인 부탁드립니다.

**Comment by dkstm95** [comment]
아, 저는 IDLE에서 스크립트 파일로 실행시켰었는데, 터미널로 해서 기다려보니 크롤이 되는군요.
