### ISSUE TITLE
궁금한게 있습니다.

### ISSUE THREAD

**Issue by kangdongkyun** [lumyjuwon/KoreaNewsCrawler#2]
def set_category(self, *args):
        for key in args:
            if self.category.get(key) is None:
                raise InvalidCategory(key)
            else:
                self.selected_category = args
이부분에서  self.selected_category 에다 args를 assign해줬는데 key를 해야하지 않는 건가 해서요...

**Comment by lumyjuwon** [comment]
아무래도 변수 명에서 혼란이 오신 것 같습니다. 
self.selected_category = key를 해줄 경우 args의 마지막 원소만 selected_category에 의해 할당될 것입니다. 
예로 들어 args = ["IT과학", "생활문화", "경제"] 일 경우에
self.selected_category = key를 하게 될 경우
`
for key in args
    self.selected_category = key
`
self.selected_category = "경제"가 됩니다.

하지만 self.selected_category는 사용자가 args를 한 모든 값을 할당해야 합니다.
그래서 args assign을 해줘야 합니다.

그리고 issue를 올려주셔서 저도 확인하게 된 것인데, 
`
def set_category(self, *args):
    for key in args:
        if self.category.get(key) is None:
            raise InvalidCategory(key)
        else:
            self.selected_category = args
` 
이것 보다는
`
def set_category(self, *args):
    for key in args:
        if self.category.get(key) is None:
            raise InvalidCategory(key)
    self.selected_category = args
`
이것이 맞다고 생각이 들어서 이와 관련해서 변수 명 및 로직 리팩토링을 해뒀습니다.

이슈 올려주셔서 감사드립니다.
